### Registrar usuário admin
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Nicolas Admin",
  "email": "admin@admin.com",
  "password": "123456",
  "role": "ADMIN"
}

### Registrar usuário Nicolas
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Nicolas",
  "email": "teste@teste.com",
  "password": "123456"
}

### Registrar usuário Eduardo
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Eduardo",
  "email": "teste2@teste2.com",
  "password": "123456"
}

### Fazer login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "123456"
}

### Criar reserva
POST http://localhost:5000/api/reservas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTU1MzM4MSwiZXhwIjoxNzQ1NTU2OTgxfQ.ume5l2K14Ctt5IeZ4VkkfH91soXznniAKeQG94QixyU

{
  "table": 5,
  "dateTime": "2025-04-25T20:00:00"
}

### Minhas reservas
GET http://localhost:5000/api/reservas/admin/todas-reservas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0NTU4NTI5NSwiZXhwIjoxNzQ1NTg4ODk1fQ.6sBuX90s3_gZNpl8sVYpNWY42qJEegrLA83_kvb6Zg4
